### ISSUE TITLE
maybe i can open a new issues of the tatic

### ISSUE THREAD

**Issue by dk-star** [Southpaw-TACTIC/Docs#16]
view this file you will there is no  LoginWdg, LoginGroupWdg to import
`
src/pyasm/prod/site/admin_tab_wdg.py`

`
line 18:  from pyasm.admin import LoginWdg, LoginGroupWdg
`

**Comment by CeltonMcGrath** [comment]
Hi dk-star,

Thanks for submitting this question. Can you sign up on the TACTIC Open Source forum?

http://forum.southpawtech.com/

**Comment by CeltonMcGrath** [comment]
Hey dk-star,

Thanks for submitting this. Can you please sign up and post in the new open source forum?

http://forum.southpawtech.com/

Best,

Celton
