### ISSUE TITLE
Using Tactic4.5~4.7 in win10 Chrome. can't check out files to local path

### ISSUE THREAD

**Issue by dishuman** [Southpaw-TACTIC/Docs#17]
Hi, I am using  Tactic4.7 in win10 Chrome.
I can't checkout files to local path.
seems it's maybe some JAVA plugin issue. I can't fix it. 
but I can checkout files in windows server 2008 with JAVA installed on IE 11.

**Comment by dishuman** [comment]
Is Tactic using NPAPI? seems current Chrome and firefox not support it anymore, is this the reason that I can't checkout files?

**Comment by CeltonMcGrath** [comment]
Hey dishuman,

Thanks for submitting this. Can you please sign up and post in the new open source forum?

http://forum.southpawtech.com/

Best,

Celton
